name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Build frontend
        run: pnpm build

      - name: Install Tauri dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev \
                              build-essential \
                              curl \
                              wget \
                              file \
                              libxdo-dev \
                              libssl-dev \
                              libayatana-appindicator3-dev \
                              librsvg2-dev

      - name: Build Tauri App
        run: pnpm tauri build
